#!/usr/bin/env tsx
/**
 * Daily report for yesterday (UTC):
 * - Finds the latest replay summary by mtime (does NOT rely on from/to fields).
 * - Falls back to `pnl_sum` (primary) or `pnl_sum_quote`.
 * - Falls back to `would_not_trade` if `would_not` missing.
 * - Computes win_rate if both would_trade and would_not_trade exist.
 * - Counts yesterday's feature rows.
 * - Writes data/arb/reports/<YYYY-MM-DD>.md
 */
import fs from "fs";
import path from "path";

const cwd = process.cwd();
const repoRoot = cwd.includes(`${path.sep}services${path.sep}arb-mm`)
  ? path.resolve(cwd, "..")
  : cwd;

const dataEnv = process.env.DATA_DIR?.trim();
const dataDir = dataEnv
  ? (path.isAbsolute(dataEnv) ? dataEnv : path.join(repoRoot, dataEnv))
  : path.join(repoRoot, "data", "arb");

const featuresDir = path.join(dataDir, "features", "sol_usdc", "v1");
const replayDir = path.join(dataDir, "replay");
const reportsDir = path.join(dataDir, "reports");

function ensureDir(p: string) { fs.mkdirSync(p, { recursive: true }); }
function ydayUtcStart(): Date { const d = new Date(); d.setUTCDate(d.getUTCDate()-1); d.setUTCHours(0,0,0,0); return d; }
function fmtDate(d: Date): string { return d.toISOString().slice(0,10); }

function latestSummaryPath(): string | null {
  if (!fs.existsSync(replayDir)) return null;
  const files = fs.readdirSync(replayDir).filter(f => f.endsWith(".summary.json"));
  if (files.length === 0) return null;
  const withStat = files.map(f => {
    const p = path.join(replayDir, f);
    const st = fs.statSync(p);
    return { p, mtime: st.mtimeMs };
  }).sort((a,b)=>b.mtime-a.mtime);
  return withStat[0].p;
}

function countFeatures(dateStr: string): number {
  const fp = path.join(featuresDir, `${dateStr}.jsonl`);
  if (!fs.existsSync(fp)) return 0;
  const buf = fs.readFileSync(fp, "utf8");
  let n = 0;
  for (const line of buf.split(/\r?\n/)) if (line.trim()) n++;
  return n;
}

function safeLoad(fp: string | null): any {
  if (!fp) return {};
  try { return JSON.parse(fs.readFileSync(fp, "utf8")); } catch { return {}; }
}

function toPct(v: number | undefined): string {
  return typeof v === "number" && isFinite(v) ? (v*100).toFixed(2)+"%" : "n/a";
}

function render(dateStr: string, sum: any, summaryPath: string | null, featuresCount: number): string {
  const wouldTrade = Number.isFinite(sum?.would_trade) ? Number(sum.would_trade) : undefined;
  const wouldNot = Number.isFinite(sum?.would_not) ? Number(sum.would_not)
                 : Number.isFinite(sum?.would_not_trade) ? Number(sum.would_not_trade)
                 : undefined;

  const pnlSum = typeof sum?.pnl_sum === "number" ? sum.pnl_sum
               : typeof sum?.pnl_sum_quote === "number" ? sum.pnl_sum_quote
               : undefined;

  let winRate: number | undefined = undefined;
  if (typeof wouldTrade === "number" && typeof wouldNot === "number" && (wouldTrade + wouldNot) > 0) {
    winRate = wouldTrade / (wouldTrade + wouldNot);
  }

  const bestEdge = typeof sum?.best_edge_bps === "number" ? sum.best_edge_bps : undefined;
  const worstEdge = typeof sum?.worst_edge_bps === "number" ? sum.worst_edge_bps : undefined;

  const params = {
    threshold_bps: sum?.threshold_bps,
    slippage_bps: sum?.slippage_bps,
    trade_size_base: sum?.trade_size_base,
    book_ttl_ms: sum?.book_ttl_ms,
    decision_dedupe_ms: sum?.decision_dedupe_ms,
    decision_bucket_ms: sum?.decision_bucket_ms,
    min_edge_delta_bps: sum?.min_edge_delta_bps,
    allow_synth_trades: sum?.allow_synth_trades
  };

  return `# Daily Report — ${dateStr}

**Symbol:** SOL/USDC
**Features (rows):** ${featuresCount}
**Would-trade:** ${wouldTrade ?? "n/a"}
**Would-not:** ${wouldNot ?? "n/a"}
**Win rate:** ${toPct(winRate)}
**PnL (sum, quote):** ${typeof pnlSum === "number" ? pnlSum.toFixed(6) : "n/a"}

**Best edge (bps):** ${typeof bestEdge === "number" ? bestEdge.toFixed(3) : "n/a"}
**Worst edge (bps):** ${typeof worstEdge === "number" ? worstEdge.toFixed(3) : "n/a"}

## Parameters
\`\`\`json
${JSON.stringify(params, null, 2)}
\`\`\`

## Files
- Summary: ${summaryPath ? path.relative(repoRoot, summaryPath) : "_not found_"}
- Features: ${path.relative(repoRoot, path.join(featuresDir, `${dateStr}.jsonl`))}

*Generated by scripts/daily_report.ts*
`;
}

(function main() {
  ensureDir(reportsDir);
  const yday = ydayUtcStart();
  const dateStr = fmtDate(yday);

  const summaryPath = latestSummaryPath(); // primary = latest by mtime
  const summary = safeLoad(summaryPath);
  const featCount = countFeatures(dateStr);

  const outPath = path.join(reportsDir, `${dateStr}.md`);
  fs.writeFileSync(outPath, render(dateStr, summary, summaryPath, featCount), "utf8");
  console.log(`Report written: ${path.relative(repoRoot, outPath)}`);
})();
